apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flight2024
  namespace: default  # Aquí va el namespace de Argo CD
spec:
  sourceRepos:
    - https://github.com/ibitabadger/labkubernetes.git  # El repositorio que contiene tu código
  destinations:
    - namespace: default  # El namespace donde se desplegará la aplicación
      server: https://kubernetes.default.svc  # El servidor de Kubernetes
  description: Proyecto para la aplicación Flight2024
